version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-docker
    ports:
     - "8080:80"
    volumes:
     - .:/code/app
    links:
     - redis
  redis:
    image: "redis:alpine"
    ports: 
     - "6379:6379"
