version: '3'
services:
  php:
    build: '.docker/php/'
    networks:
      - backend
    volumes:
     - .:/code/app
    container_name: php

  apache:
    build: '.docker/apache/'
    ports:
     - "8080:80"
    depends_on:
      - php
      - redis
    networks:
      - backend
      - frontend
    volumes:
      - .:/code/app
    container_name: apache

  redis:
    image: "redis:alpine"
    networks:
      - backend
    ports: 
     - "6379:6379"
    container_name: redis

  elastic:
    image: elasticsearch:1.7
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend
    container_name: elastic

networks:
  frontend:
  backend: